// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/elasticactors.proto

package org.elasterix.elasticactors.serialization.protobuf;

public final class Elasticactors {
  private Elasticactors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InternalMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string receiver = 1;
    boolean hasReceiver();
    String getReceiver();
    
    // optional string sender = 2;
    boolean hasSender();
    String getSender();
    
    // required string payloadClass = 3;
    boolean hasPayloadClass();
    String getPayloadClass();
    
    // required bytes payload = 4;
    boolean hasPayload();
    com.google.protobuf.ByteString getPayload();
    
    // required bytes id = 5;
    boolean hasId();
    com.google.protobuf.ByteString getId();
  }
  public static final class InternalMessage extends
      com.google.protobuf.GeneratedMessage
      implements InternalMessageOrBuilder {
    // Use InternalMessage.newBuilder() to construct.
    private InternalMessage(Builder builder) {
      super(builder);
    }
    private InternalMessage(boolean noInit) {}
    
    private static final InternalMessage defaultInstance;
    public static InternalMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public InternalMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string receiver = 1;
    public static final int RECEIVER_FIELD_NUMBER = 1;
    private java.lang.Object receiver_;
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          receiver_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string sender = 2;
    public static final int SENDER_FIELD_NUMBER = 2;
    private java.lang.Object sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sender_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string payloadClass = 3;
    public static final int PAYLOADCLASS_FIELD_NUMBER = 3;
    private java.lang.Object payloadClass_;
    public boolean hasPayloadClass() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPayloadClass() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          payloadClass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPayloadClassBytes() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        payloadClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes payload = 4;
    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    
    // required bytes id = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    
    private void initFields() {
      receiver_ = "";
      sender_ = "";
      payloadClass_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      id_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPayloadClass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReceiverBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSenderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPayloadClassBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, payload_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, id_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReceiverBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSenderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPayloadClassBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable;
      }
      
      // Construct using org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        receiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        payloadClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.getDescriptor();
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage getDefaultInstanceForType() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.getDefaultInstance();
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage build() {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage buildPartial() {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage result = new org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payloadClass_ = payloadClass_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage) {
          return mergeFrom((org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage other) {
        if (other == org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.getDefaultInstance()) return this;
        if (other.hasReceiver()) {
          setReceiver(other.getReceiver());
        }
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasPayloadClass()) {
          setPayloadClass(other.getPayloadClass());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPayloadClass()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              receiver_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sender_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              payloadClass_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              payload_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              id_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string receiver = 1;
      private java.lang.Object receiver_ = "";
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReceiver(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        receiver_ = value;
        onChanged();
        return this;
      }
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000001);
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      void setReceiver(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        receiver_ = value;
        onChanged();
      }
      
      // optional string sender = 2;
      private java.lang.Object sender_ = "";
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSender(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      void setSender(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
      }
      
      // required string payloadClass = 3;
      private java.lang.Object payloadClass_ = "";
      public boolean hasPayloadClass() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPayloadClass() {
        java.lang.Object ref = payloadClass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          payloadClass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPayloadClass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payloadClass_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayloadClass() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payloadClass_ = getDefaultInstance().getPayloadClass();
        onChanged();
        return this;
      }
      void setPayloadClass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        payloadClass_ = value;
        onChanged();
      }
      
      // required bytes payload = 4;
      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      
      // required bytes id = 5;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.elasterix.elasticactors.serialization.protobuf.InternalMessage)
    }
    
    static {
      defaultInstance = new InternalMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.elasterix.elasticactors.serialization.protobuf.InternalMessage)
  }
  
  public interface PersistentActorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string actorRef = 1;
    boolean hasActorRef();
    String getActorRef();
    
    // required string actorClass = 2;
    boolean hasActorClass();
    String getActorClass();
    
    // required string actorSystemVersion = 3;
    boolean hasActorSystemVersion();
    String getActorSystemVersion();
    
    // optional bytes state = 4;
    boolean hasState();
    com.google.protobuf.ByteString getState();
  }
  public static final class PersistentActor extends
      com.google.protobuf.GeneratedMessage
      implements PersistentActorOrBuilder {
    // Use PersistentActor.newBuilder() to construct.
    private PersistentActor(Builder builder) {
      super(builder);
    }
    private PersistentActor(boolean noInit) {}
    
    private static final PersistentActor defaultInstance;
    public static PersistentActor getDefaultInstance() {
      return defaultInstance;
    }
    
    public PersistentActor getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string actorRef = 1;
    public static final int ACTORREF_FIELD_NUMBER = 1;
    private java.lang.Object actorRef_;
    public boolean hasActorRef() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getActorRef() {
      java.lang.Object ref = actorRef_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actorRef_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActorRefBytes() {
      java.lang.Object ref = actorRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actorRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string actorClass = 2;
    public static final int ACTORCLASS_FIELD_NUMBER = 2;
    private java.lang.Object actorClass_;
    public boolean hasActorClass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getActorClass() {
      java.lang.Object ref = actorClass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actorClass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActorClassBytes() {
      java.lang.Object ref = actorClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actorClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string actorSystemVersion = 3;
    public static final int ACTORSYSTEMVERSION_FIELD_NUMBER = 3;
    private java.lang.Object actorSystemVersion_;
    public boolean hasActorSystemVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getActorSystemVersion() {
      java.lang.Object ref = actorSystemVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actorSystemVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActorSystemVersionBytes() {
      java.lang.Object ref = actorSystemVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actorSystemVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes state = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getState() {
      return state_;
    }
    
    private void initFields() {
      actorRef_ = "";
      actorClass_ = "";
      actorSystemVersion_ = "";
      state_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasActorRef()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActorClass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActorSystemVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getActorRefBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getActorClassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getActorSystemVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, state_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getActorRefBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getActorClassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getActorSystemVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_fieldAccessorTable;
      }
      
      // Construct using org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        actorRef_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        actorClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        actorSystemVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.getDescriptor();
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor getDefaultInstanceForType() {
        return org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.getDefaultInstance();
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor build() {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor buildPartial() {
        org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor result = new org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.actorRef_ = actorRef_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actorClass_ = actorClass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.actorSystemVersion_ = actorSystemVersion_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor) {
          return mergeFrom((org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor other) {
        if (other == org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.getDefaultInstance()) return this;
        if (other.hasActorRef()) {
          setActorRef(other.getActorRef());
        }
        if (other.hasActorClass()) {
          setActorClass(other.getActorClass());
        }
        if (other.hasActorSystemVersion()) {
          setActorSystemVersion(other.getActorSystemVersion());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasActorRef()) {
          
          return false;
        }
        if (!hasActorClass()) {
          
          return false;
        }
        if (!hasActorSystemVersion()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              actorRef_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              actorClass_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              actorSystemVersion_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              state_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string actorRef = 1;
      private java.lang.Object actorRef_ = "";
      public boolean hasActorRef() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getActorRef() {
        java.lang.Object ref = actorRef_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actorRef_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActorRef(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        actorRef_ = value;
        onChanged();
        return this;
      }
      public Builder clearActorRef() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actorRef_ = getDefaultInstance().getActorRef();
        onChanged();
        return this;
      }
      void setActorRef(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        actorRef_ = value;
        onChanged();
      }
      
      // required string actorClass = 2;
      private java.lang.Object actorClass_ = "";
      public boolean hasActorClass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getActorClass() {
        java.lang.Object ref = actorClass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actorClass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActorClass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actorClass_ = value;
        onChanged();
        return this;
      }
      public Builder clearActorClass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actorClass_ = getDefaultInstance().getActorClass();
        onChanged();
        return this;
      }
      void setActorClass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        actorClass_ = value;
        onChanged();
      }
      
      // required string actorSystemVersion = 3;
      private java.lang.Object actorSystemVersion_ = "";
      public boolean hasActorSystemVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getActorSystemVersion() {
        java.lang.Object ref = actorSystemVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actorSystemVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActorSystemVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        actorSystemVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearActorSystemVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        actorSystemVersion_ = getDefaultInstance().getActorSystemVersion();
        onChanged();
        return this;
      }
      void setActorSystemVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        actorSystemVersion_ = value;
        onChanged();
      }
      
      // optional bytes state = 4;
      private com.google.protobuf.ByteString state_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getState() {
        return state_;
      }
      public Builder setState(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.elasterix.elasticactors.serialization.protobuf.PersistentActor)
    }
    
    static {
      defaultInstance = new PersistentActor(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.elasterix.elasticactors.serialization.protobuf.PersistentActor)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/protobuf/elasticactors.proto\022" +
      "2org.elasterix.elasticactors.serializati" +
      "on.protobuf\"f\n\017InternalMessage\022\020\n\010receiv" +
      "er\030\001 \001(\t\022\016\n\006sender\030\002 \001(\t\022\024\n\014payloadClass" +
      "\030\003 \002(\t\022\017\n\007payload\030\004 \002(\014\022\n\n\002id\030\005 \002(\014\"b\n\017P" +
      "ersistentActor\022\020\n\010actorRef\030\001 \002(\t\022\022\n\nacto" +
      "rClass\030\002 \002(\t\022\032\n\022actorSystemVersion\030\003 \002(\t" +
      "\022\r\n\005state\030\004 \001(\014B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_elasterix_elasticactors_serialization_protobuf_InternalMessage_descriptor,
              new java.lang.String[] { "Receiver", "Sender", "PayloadClass", "Payload", "Id", },
              org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.class,
              org.elasterix.elasticactors.serialization.protobuf.Elasticactors.InternalMessage.Builder.class);
          internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_elasterix_elasticactors_serialization_protobuf_PersistentActor_descriptor,
              new java.lang.String[] { "ActorRef", "ActorClass", "ActorSystemVersion", "State", },
              org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.class,
              org.elasterix.elasticactors.serialization.protobuf.Elasticactors.PersistentActor.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
