// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/clustering.proto
// Protobuf Java Version: 4.29.3

package org.elasticsoftware.elasticactors.cluster.protobuf;

public final class Clustering {
  private Clustering() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Clustering.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClusterMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     * @return Whether the shardReleased field is set.
     */
    boolean hasShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     * @return The shardReleased.
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder();

    /**
     * <code>optional int64 viewId = 2;</code>
     * @return Whether the viewId field is set.
     */
    boolean hasViewId();
    /**
     * <code>optional int64 viewId = 2;</code>
     * @return The viewId.
     */
    long getViewId();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
   */
  public static final class ClusterMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      ClusterMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ClusterMessage.class.getName());
    }
    // Use ClusterMessage.newBuilder() to construct.
    private ClusterMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClusterMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
    }

    private int bitField0_;
    public static final int SHARDRELEASED_FIELD_NUMBER = 1;
    private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_;
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     * @return Whether the shardReleased field is set.
     */
    @java.lang.Override
    public boolean hasShardReleased() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     * @return The shardReleased.
     */
    @java.lang.Override
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
      return shardReleased_ == null ? org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    @java.lang.Override
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
      return shardReleased_ == null ? org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
    }

    public static final int VIEWID_FIELD_NUMBER = 2;
    private long viewId_ = 0L;
    /**
     * <code>optional int64 viewId = 2;</code>
     * @return Whether the viewId field is set.
     */
    @java.lang.Override
    public boolean hasViewId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 viewId = 2;</code>
     * @return The viewId.
     */
    @java.lang.Override
    public long getViewId() {
      return viewId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getShardReleased());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, viewId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getShardReleased());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, viewId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage)) {
        return super.equals(obj);
      }
      org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage other = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) obj;

      if (hasShardReleased() != other.hasShardReleased()) return false;
      if (hasShardReleased()) {
        if (!getShardReleased()
            .equals(other.getShardReleased())) return false;
      }
      if (hasViewId() != other.hasViewId()) return false;
      if (hasViewId()) {
        if (getViewId()
            != other.getViewId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShardReleased()) {
        hash = (37 * hash) + SHARDRELEASED_FIELD_NUMBER;
        hash = (53 * hash) + getShardReleased().hashCode();
      }
      if (hasViewId()) {
        hash = (37 * hash) + VIEWID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getViewId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getShardReleasedFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        shardReleased_ = null;
        if (shardReleasedBuilder_ != null) {
          shardReleasedBuilder_.dispose();
          shardReleasedBuilder_ = null;
        }
        viewId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstanceForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.shardReleased_ = shardReleasedBuilder_ == null
              ? shardReleased_
              : shardReleasedBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.viewId_ = viewId_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage other) {
        if (other == org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.getDefaultInstance()) return this;
        if (other.hasShardReleased()) {
          mergeShardReleased(other.getShardReleased());
        }
        if (other.hasViewId()) {
          setViewId(other.getViewId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getShardReleasedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                viewId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_;
      private com.google.protobuf.SingleFieldBuilder<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> shardReleasedBuilder_;
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       * @return Whether the shardReleased field is set.
       */
      public boolean hasShardReleased() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       * @return The shardReleased.
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
        if (shardReleasedBuilder_ == null) {
          return shardReleased_ == null ? org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
        } else {
          return shardReleasedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shardReleased_ = value;
        } else {
          shardReleasedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder builderForValue) {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = builderForValue.build();
        } else {
          shardReleasedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder mergeShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            shardReleased_ != null &&
            shardReleased_ != org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance()) {
            getShardReleasedBuilder().mergeFrom(value);
          } else {
            shardReleased_ = value;
          }
        } else {
          shardReleasedBuilder_.mergeFrom(value);
        }
        if (shardReleased_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder clearShardReleased() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shardReleased_ = null;
        if (shardReleasedBuilder_ != null) {
          shardReleasedBuilder_.dispose();
          shardReleasedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder getShardReleasedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getShardReleasedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
        if (shardReleasedBuilder_ != null) {
          return shardReleasedBuilder_.getMessageOrBuilder();
        } else {
          return shardReleased_ == null ?
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> 
          getShardReleasedFieldBuilder() {
        if (shardReleasedBuilder_ == null) {
          shardReleasedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder>(
                  getShardReleased(),
                  getParentForChildren(),
                  isClean());
          shardReleased_ = null;
        }
        return shardReleasedBuilder_;
      }

      private long viewId_ ;
      /**
       * <code>optional int64 viewId = 2;</code>
       * @return Whether the viewId field is set.
       */
      @java.lang.Override
      public boolean hasViewId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       * @return The viewId.
       */
      @java.lang.Override
      public long getViewId() {
        return viewId_;
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       * @param value The viewId to set.
       * @return This builder for chaining.
       */
      public Builder setViewId(long value) {

        viewId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearViewId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        viewId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    private static final org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClusterMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClusterMessage>() {
      @java.lang.Override
      public ClusterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClusterMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShardReleasedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 shardId = 1;</code>
     * @return Whether the shardId field is set.
     */
    boolean hasShardId();
    /**
     * <code>optional int32 shardId = 1;</code>
     * @return The shardId.
     */
    int getShardId();

    /**
     * <code>optional string actorSystem = 2;</code>
     * @return Whether the actorSystem field is set.
     */
    boolean hasActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     * @return The actorSystem.
     */
    java.lang.String getActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     * @return The bytes for actorSystem.
     */
    com.google.protobuf.ByteString
        getActorSystemBytes();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
   */
  public static final class ShardReleased extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      ShardReleasedOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ShardReleased.class.getName());
    }
    // Use ShardReleased.newBuilder() to construct.
    private ShardReleased(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ShardReleased() {
      actorSystem_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
    }

    private int bitField0_;
    public static final int SHARDID_FIELD_NUMBER = 1;
    private int shardId_ = 0;
    /**
     * <code>optional int32 shardId = 1;</code>
     * @return Whether the shardId field is set.
     */
    @java.lang.Override
    public boolean hasShardId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 shardId = 1;</code>
     * @return The shardId.
     */
    @java.lang.Override
    public int getShardId() {
      return shardId_;
    }

    public static final int ACTORSYSTEM_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object actorSystem_ = "";
    /**
     * <code>optional string actorSystem = 2;</code>
     * @return Whether the actorSystem field is set.
     */
    @java.lang.Override
    public boolean hasActorSystem() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     * @return The actorSystem.
     */
    @java.lang.Override
    public java.lang.String getActorSystem() {
      java.lang.Object ref = actorSystem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          actorSystem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     * @return The bytes for actorSystem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActorSystemBytes() {
      java.lang.Object ref = actorSystem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, actorSystem_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, actorSystem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased)) {
        return super.equals(obj);
      }
      org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased other = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) obj;

      if (hasShardId() != other.hasShardId()) return false;
      if (hasShardId()) {
        if (getShardId()
            != other.getShardId()) return false;
      }
      if (hasActorSystem() != other.hasActorSystem()) return false;
      if (hasActorSystem()) {
        if (!getActorSystem()
            .equals(other.getActorSystem())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShardId()) {
        hash = (37 * hash) + SHARDID_FIELD_NUMBER;
        hash = (53 * hash) + getShardId();
      }
      if (hasActorSystem()) {
        hash = (37 * hash) + ACTORSYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getActorSystem().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        shardId_ = 0;
        actorSystem_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstanceForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.shardId_ = shardId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.actorSystem_ = actorSystem_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased other) {
        if (other == org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance()) return this;
        if (other.hasShardId()) {
          setShardId(other.getShardId());
        }
        if (other.hasActorSystem()) {
          actorSystem_ = other.actorSystem_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                shardId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                actorSystem_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int shardId_ ;
      /**
       * <code>optional int32 shardId = 1;</code>
       * @return Whether the shardId field is set.
       */
      @java.lang.Override
      public boolean hasShardId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       * @return The shardId.
       */
      @java.lang.Override
      public int getShardId() {
        return shardId_;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       * @param value The shardId to set.
       * @return This builder for chaining.
       */
      public Builder setShardId(int value) {

        shardId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearShardId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shardId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object actorSystem_ = "";
      /**
       * <code>optional string actorSystem = 2;</code>
       * @return Whether the actorSystem field is set.
       */
      public boolean hasActorSystem() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       * @return The actorSystem.
       */
      public java.lang.String getActorSystem() {
        java.lang.Object ref = actorSystem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            actorSystem_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       * @return The bytes for actorSystem.
       */
      public com.google.protobuf.ByteString
          getActorSystemBytes() {
        java.lang.Object ref = actorSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actorSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       * @param value The actorSystem to set.
       * @return This builder for chaining.
       */
      public Builder setActorSystem(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        actorSystem_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearActorSystem() {
        actorSystem_ = getDefaultInstance().getActorSystem();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       * @param value The bytes for actorSystem to set.
       * @return This builder for chaining.
       */
      public Builder setActorSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        actorSystem_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    private static final org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShardReleased>
        PARSER = new com.google.protobuf.AbstractParser<ShardReleased>() {
      @java.lang.Override
      public ShardReleased parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShardReleased> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShardReleased> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/protobuf/clustering.proto\0222or" +
      "g.elasticsoftware.elasticactors.cluster." +
      "protobuf\"z\n\016ClusterMessage\022X\n\rshardRelea" +
      "sed\030\001 \001(\0132A.org.elasticsoftware.elastica" +
      "ctors.cluster.protobuf.ShardReleased\022\016\n\006" +
      "viewId\030\002 \001(\003\"5\n\rShardReleased\022\017\n\007shardId" +
      "\030\001 \001(\005\022\023\n\013actorSystem\030\002 \001(\tB\002H\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor,
        new java.lang.String[] { "ShardReleased", "ViewId", });
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor,
        new java.lang.String[] { "ShardId", "ActorSystem", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
