/*
 * Copyright 2013 - 2016 The Original Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clustering.proto

package org.elasticsoftware.elasticactors.cluster.protobuf;

public final class Clustering {
  private Clustering() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClusterMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    boolean hasShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
   */
  public static final class ClusterMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClusterMessageOrBuilder {
    // Use ClusterMessage.newBuilder() to construct.
    private ClusterMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClusterMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClusterMessage defaultInstance;
    public static ClusterMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ClusterMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClusterMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = shardReleased_.toBuilder();
              }
              shardReleased_ = input.readMessage(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(shardReleased_);
                shardReleased_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ClusterMessage> PARSER =
        new com.google.protobuf.AbstractParser<ClusterMessage>() {
      public ClusterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClusterMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;
    public static final int SHARDRELEASED_FIELD_NUMBER = 1;
    private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_;
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public boolean hasShardReleased() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
      return shardReleased_;
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
      return shardReleased_;
    }

    private void initFields() {
      shardReleased_ = org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, shardReleased_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, shardReleased_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getShardReleasedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
        } else {
          shardReleasedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstanceForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.getDefaultInstance();
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (shardReleasedBuilder_ == null) {
          result.shardReleased_ = shardReleased_;
        } else {
          result.shardReleased_ = shardReleasedBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage other) {
        if (other == org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.getDefaultInstance()) return this;
        if (other.hasShardReleased()) {
          mergeShardReleased(other.getShardReleased());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;
      private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_ = org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> shardReleasedBuilder_;
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public boolean hasShardReleased() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
        if (shardReleasedBuilder_ == null) {
          return shardReleased_;
        } else {
          return shardReleasedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shardReleased_ = value;
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder builderForValue) {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = builderForValue.build();
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder mergeShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              shardReleased_ != org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance()) {
            shardReleased_ =
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder(shardReleased_).mergeFrom(value).buildPartial();
          } else {
            shardReleased_ = value;
          }
          onChanged();
        } else {
          shardReleasedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder clearShardReleased() {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
          onChanged();
        } else {
          shardReleasedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder getShardReleasedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getShardReleasedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
        if (shardReleasedBuilder_ != null) {
          return shardReleasedBuilder_.getMessageOrBuilder();
        } else {
          return shardReleased_;
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> 
          getShardReleasedFieldBuilder() {
        if (shardReleasedBuilder_ == null) {
          shardReleasedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder>(
                  shardReleased_,
                  getParentForChildren(),
                  isClean());
          shardReleased_ = null;
        }
        return shardReleasedBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    }

    static {
      defaultInstance = new ClusterMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
  }

  public interface ShardReleasedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 shardId = 1;
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    boolean hasShardId();
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    int getShardId();

    // optional string actorSystem = 2;
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    boolean hasActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    java.lang.String getActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    com.google.protobuf.ByteString
        getActorSystemBytes();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
   */
  public static final class ShardReleased extends
      com.google.protobuf.GeneratedMessage
      implements ShardReleasedOrBuilder {
    // Use ShardReleased.newBuilder() to construct.
    private ShardReleased(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ShardReleased(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ShardReleased defaultInstance;
    public static ShardReleased getDefaultInstance() {
      return defaultInstance;
    }

    public ShardReleased getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ShardReleased(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              shardId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              actorSystem_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
    }

    public static com.google.protobuf.Parser<ShardReleased> PARSER =
        new com.google.protobuf.AbstractParser<ShardReleased>() {
      public ShardReleased parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShardReleased(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ShardReleased> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 shardId = 1;
    public static final int SHARDID_FIELD_NUMBER = 1;
    private int shardId_;
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    public boolean hasShardId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    public int getShardId() {
      return shardId_;
    }

    // optional string actorSystem = 2;
    public static final int ACTORSYSTEM_FIELD_NUMBER = 2;
    private java.lang.Object actorSystem_;
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public boolean hasActorSystem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public java.lang.String getActorSystem() {
      java.lang.Object ref = actorSystem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          actorSystem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActorSystemBytes() {
      java.lang.Object ref = actorSystem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      shardId_ = 0;
      actorSystem_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getActorSystemBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getActorSystemBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        shardId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        actorSystem_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstanceForType() {
        return org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance();
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shardId_ = shardId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actorSystem_ = actorSystem_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased other) {
        if (other == org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance()) return this;
        if (other.hasShardId()) {
          setShardId(other.getShardId());
        }
        if (other.hasActorSystem()) {
          bitField0_ |= 0x00000002;
          actorSystem_ = other.actorSystem_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 shardId = 1;
      private int shardId_ ;
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public boolean hasShardId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public int getShardId() {
        return shardId_;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public Builder setShardId(int value) {
        bitField0_ |= 0x00000001;
        shardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public Builder clearShardId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shardId_ = 0;
        onChanged();
        return this;
      }

      // optional string actorSystem = 2;
      private java.lang.Object actorSystem_ = "";
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public boolean hasActorSystem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public java.lang.String getActorSystem() {
        java.lang.Object ref = actorSystem_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          actorSystem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public com.google.protobuf.ByteString
          getActorSystemBytes() {
        java.lang.Object ref = actorSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actorSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder setActorSystem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actorSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder clearActorSystem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actorSystem_ = getDefaultInstance().getActorSystem();
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder setActorSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actorSystem_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    }

    static {
      defaultInstance = new ShardReleased(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020clustering.proto\0222org.elasticsoftware." +
      "elasticactors.cluster.protobuf\"j\n\016Cluste" +
      "rMessage\022X\n\rshardReleased\030\001 \001(\0132A.org.el" +
      "asticsoftware.elasticactors.cluster.prot" +
      "obuf.ShardReleased\"5\n\rShardReleased\022\017\n\007s" +
      "hardId\030\001 \001(\005\022\023\n\013actorSystem\030\002 \001(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor,
              new java.lang.String[] { "ShardReleased", });
          internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor,
              new java.lang.String[] { "ShardId", "ActorSystem", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
