// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clustering.proto

package org.elasticsoftware.elasticactors.cluster.protobuf;

public final class Clustering {
  private Clustering() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClusterMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    boolean hasShardReleased();
    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased();
    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder();

    /**
     * <code>int64 viewId = 2;</code>
     */
    long getViewId();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
   */
  public  static final class ClusterMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      ClusterMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClusterMessage.newBuilder() to construct.
    private ClusterMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClusterMessage() {
      viewId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClusterMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder subBuilder = null;
              if (shardReleased_ != null) {
                subBuilder = shardReleased_.toBuilder();
              }
              shardReleased_ = input.readMessage(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(shardReleased_);
                shardReleased_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              viewId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
    }

    public static final int SHARDRELEASED_FIELD_NUMBER = 1;
    private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_;
    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public boolean hasShardReleased() {
      return shardReleased_ != null;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
      return shardReleased_ == null ? org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
    }
    /**
     * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
      return getShardReleased();
    }

    public static final int VIEWID_FIELD_NUMBER = 2;
    private long viewId_;
    /**
     * <code>int64 viewId = 2;</code>
     */
    public long getViewId() {
      return viewId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (shardReleased_ != null) {
        output.writeMessage(1, getShardReleased());
      }
      if (viewId_ != 0L) {
        output.writeInt64(2, viewId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (shardReleased_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getShardReleased());
      }
      if (viewId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, viewId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage)) {
        return super.equals(obj);
      }
      org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage other = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) obj;

      boolean result = true;
      result = result && (hasShardReleased() == other.hasShardReleased());
      if (hasShardReleased()) {
        result = result && getShardReleased()
            .equals(other.getShardReleased());
      }
      result = result && (getViewId()
          == other.getViewId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShardReleased()) {
        hash = (37 * hash) + SHARDRELEASED_FIELD_NUMBER;
        hash = (53 * hash) + getShardReleased().hashCode();
      }
      hash = (37 * hash) + VIEWID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getViewId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = null;
        } else {
          shardReleased_ = null;
          shardReleasedBuilder_ = null;
        }
        viewId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage(this);
        if (shardReleasedBuilder_ == null) {
          result.shardReleased_ = shardReleased_;
        } else {
          result.shardReleased_ = shardReleasedBuilder_.build();
        }
        result.viewId_ = viewId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasShardReleased()) {
          mergeShardReleased(other.getShardReleased());
        }
        if (other.getViewId() != 0L) {
          setViewId(other.getViewId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased shardReleased_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> shardReleasedBuilder_;
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public boolean hasShardReleased() {
        return shardReleasedBuilder_ != null || shardReleased_ != null;
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getShardReleased() {
        if (shardReleasedBuilder_ == null) {
          return shardReleased_ == null ? org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
        } else {
          return shardReleasedBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shardReleased_ = value;
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder builderForValue) {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = builderForValue.build();
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder mergeShardReleased(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (shardReleased_ != null) {
            shardReleased_ =
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder(shardReleased_).mergeFrom(value).buildPartial();
          } else {
            shardReleased_ = value;
          }
          onChanged();
        } else {
          shardReleasedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder clearShardReleased() {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = null;
          onChanged();
        } else {
          shardReleased_ = null;
          shardReleasedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder getShardReleasedBuilder() {
        
        onChanged();
        return getShardReleasedFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder getShardReleasedOrBuilder() {
        if (shardReleasedBuilder_ != null) {
          return shardReleasedBuilder_.getMessageOrBuilder();
        } else {
          return shardReleased_ == null ?
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.getDefaultInstance() : shardReleased_;
        }
      }
      /**
       * <code>.org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder> 
          getShardReleasedFieldBuilder() {
        if (shardReleasedBuilder_ == null) {
          shardReleasedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder>(
                  getShardReleased(),
                  getParentForChildren(),
                  isClean());
          shardReleased_ = null;
        }
        return shardReleasedBuilder_;
      }

      private long viewId_ ;
      /**
       * <code>int64 viewId = 2;</code>
       */
      public long getViewId() {
        return viewId_;
      }
      /**
       * <code>int64 viewId = 2;</code>
       */
      public Builder setViewId(long value) {
        
        viewId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 viewId = 2;</code>
       */
      public Builder clearViewId() {
        
        viewId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    private static final org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClusterMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClusterMessage>() {
      public ClusterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClusterMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClusterMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClusterMessage> getParserForType() {
      return PARSER;
    }

    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShardReleasedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 shardId = 1;</code>
     */
    int getShardId();

    /**
     * <code>string actorSystem = 2;</code>
     */
    String getActorSystem();
    /**
     * <code>string actorSystem = 2;</code>
     */
    com.google.protobuf.ByteString
        getActorSystemBytes();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
   */
  public  static final class ShardReleased extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      ShardReleasedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShardReleased.newBuilder() to construct.
    private ShardReleased(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShardReleased() {
      shardId_ = 0;
      actorSystem_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShardReleased(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              shardId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              actorSystem_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
    }

    public static final int SHARDID_FIELD_NUMBER = 1;
    private int shardId_;
    /**
     * <code>int32 shardId = 1;</code>
     */
    public int getShardId() {
      return shardId_;
    }

    public static final int ACTORSYSTEM_FIELD_NUMBER = 2;
    private volatile Object actorSystem_;
    /**
     * <code>string actorSystem = 2;</code>
     */
    public String getActorSystem() {
      Object ref = actorSystem_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        actorSystem_ = s;
        return s;
      }
    }
    /**
     * <code>string actorSystem = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActorSystemBytes() {
      Object ref = actorSystem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        actorSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (shardId_ != 0) {
        output.writeInt32(1, shardId_);
      }
      if (!getActorSystemBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, actorSystem_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (shardId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, shardId_);
      }
      if (!getActorSystemBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, actorSystem_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased)) {
        return super.equals(obj);
      }
      org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased other = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) obj;

      boolean result = true;
      result = result && (getShardId()
          == other.getShardId());
      result = result && getActorSystem()
          .equals(other.getActorSystem());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHARDID_FIELD_NUMBER;
      hash = (53 * hash) + getShardId();
      hash = (37 * hash) + ACTORSYSTEM_FIELD_NUMBER;
      hash = (53 * hash) + getActorSystem().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleasedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.class, org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        shardId_ = 0;

        actorSystem_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased build() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased buildPartial() {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased result = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased(this);
        result.shardId_ = shardId_;
        result.actorSystem_ = actorSystem_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) {
          return mergeFrom((org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased other) {
        if (other == getDefaultInstance()) return this;
        if (other.getShardId() != 0) {
          setShardId(other.getShardId());
        }
        if (!other.getActorSystem().isEmpty()) {
          actorSystem_ = other.actorSystem_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int shardId_ ;
      /**
       * <code>int32 shardId = 1;</code>
       */
      public int getShardId() {
        return shardId_;
      }
      /**
       * <code>int32 shardId = 1;</code>
       */
      public Builder setShardId(int value) {
        
        shardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 shardId = 1;</code>
       */
      public Builder clearShardId() {
        
        shardId_ = 0;
        onChanged();
        return this;
      }

      private Object actorSystem_ = "";
      /**
       * <code>string actorSystem = 2;</code>
       */
      public String getActorSystem() {
        Object ref = actorSystem_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          actorSystem_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string actorSystem = 2;</code>
       */
      public com.google.protobuf.ByteString
          getActorSystemBytes() {
        Object ref = actorSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          actorSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actorSystem = 2;</code>
       */
      public Builder setActorSystem(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actorSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actorSystem = 2;</code>
       */
      public Builder clearActorSystem() {
        
        actorSystem_ = getDefaultInstance().getActorSystem();
        onChanged();
        return this;
      }
      /**
       * <code>string actorSystem = 2;</code>
       */
      public Builder setActorSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actorSystem_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    private static final org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased();
    }

    public static org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShardReleased>
        PARSER = new com.google.protobuf.AbstractParser<ShardReleased>() {
      public ShardReleased parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShardReleased(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShardReleased> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ShardReleased> getParserForType() {
      return PARSER;
    }

    public org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020clustering.proto\0222org.elasticsoftware." +
      "elasticactors.cluster.protobuf\"z\n\016Cluste" +
      "rMessage\022X\n\rshardReleased\030\001 \001(\0132A.org.el" +
      "asticsoftware.elasticactors.cluster.prot" +
      "obuf.ShardReleased\022\016\n\006viewId\030\002 \001(\003\"5\n\rSh" +
      "ardReleased\022\017\n\007shardId\030\001 \001(\005\022\023\n\013actorSys" +
      "tem\030\002 \001(\tB\002H\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor,
        new String[] { "ShardReleased", "ViewId", });
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor,
        new String[] { "ShardId", "ActorSystem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
