/*
 *   Copyright 2013 - 2019 The Original Authors
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clustering.proto

package org.elasticsoftware.elasticactors.cluster.protobuf;

public final class Clustering {
  private Clustering() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClusterMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    boolean hasShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    ShardReleased getShardReleased();
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    ShardReleasedOrBuilder getShardReleasedOrBuilder();

    /**
     * <code>optional int64 viewId = 2;</code>
     */
    boolean hasViewId();
    /**
     * <code>optional int64 viewId = 2;</code>
     */
    long getViewId();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
   */
  public  static final class ClusterMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
      ClusterMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClusterMessage.newBuilder() to construct.
    private ClusterMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClusterMessage() {
      viewId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClusterMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ShardReleased.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = shardReleased_.toBuilder();
              }
              shardReleased_ = input.readMessage(ShardReleased.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(shardReleased_);
                shardReleased_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              viewId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClusterMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int SHARDRELEASED_FIELD_NUMBER = 1;
    private ShardReleased shardReleased_;
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public boolean hasShardReleased() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public ShardReleased getShardReleased() {
      return shardReleased_ == null ? ShardReleased.getDefaultInstance() : shardReleased_;
    }
    /**
     * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
     */
    public ShardReleasedOrBuilder getShardReleasedOrBuilder() {
      return shardReleased_ == null ? ShardReleased.getDefaultInstance() : shardReleased_;
    }

    public static final int VIEWID_FIELD_NUMBER = 2;
    private long viewId_;
    /**
     * <code>optional int64 viewId = 2;</code>
     */
    public boolean hasViewId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 viewId = 2;</code>
     */
    public long getViewId() {
      return viewId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getShardReleased());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, viewId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getShardReleased());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, viewId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClusterMessage)) {
        return super.equals(obj);
      }
      ClusterMessage other = (ClusterMessage) obj;

      boolean result = true;
      result = result && (hasShardReleased() == other.hasShardReleased());
      if (hasShardReleased()) {
        result = result && getShardReleased()
            .equals(other.getShardReleased());
      }
      result = result && (hasViewId() == other.hasViewId());
      if (hasViewId()) {
        result = result && (getViewId()
            == other.getViewId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShardReleased()) {
        hash = (37 * hash) + SHARDRELEASED_FIELD_NUMBER;
        hash = (53 * hash) + getShardReleased().hashCode();
      }
      if (hasViewId()) {
        hash = (37 * hash) + VIEWID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getViewId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClusterMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClusterMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClusterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClusterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClusterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClusterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClusterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClusterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClusterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClusterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClusterMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
        ClusterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClusterMessage.class, Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ClusterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getShardReleasedFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = null;
        } else {
          shardReleasedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        viewId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
      }

      public ClusterMessage getDefaultInstanceForType() {
        return ClusterMessage.getDefaultInstance();
      }

      public ClusterMessage build() {
        ClusterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClusterMessage buildPartial() {
        ClusterMessage result = new ClusterMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (shardReleasedBuilder_ == null) {
          result.shardReleased_ = shardReleased_;
        } else {
          result.shardReleased_ = shardReleasedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.viewId_ = viewId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClusterMessage) {
          return mergeFrom((ClusterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClusterMessage other) {
        if (other == ClusterMessage.getDefaultInstance()) return this;
        if (other.hasShardReleased()) {
          mergeShardReleased(other.getShardReleased());
        }
        if (other.hasViewId()) {
          setViewId(other.getViewId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClusterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClusterMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ShardReleased shardReleased_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ShardReleased, ShardReleased.Builder, ShardReleasedOrBuilder> shardReleasedBuilder_;
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public boolean hasShardReleased() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public ShardReleased getShardReleased() {
        if (shardReleasedBuilder_ == null) {
          return shardReleased_ == null ? ShardReleased.getDefaultInstance() : shardReleased_;
        } else {
          return shardReleasedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shardReleased_ = value;
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder setShardReleased(
          ShardReleased.Builder builderForValue) {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = builderForValue.build();
          onChanged();
        } else {
          shardReleasedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder mergeShardReleased(ShardReleased value) {
        if (shardReleasedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              shardReleased_ != null &&
              shardReleased_ != ShardReleased.getDefaultInstance()) {
            shardReleased_ =
              ShardReleased.newBuilder(shardReleased_).mergeFrom(value).buildPartial();
          } else {
            shardReleased_ = value;
          }
          onChanged();
        } else {
          shardReleasedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public Builder clearShardReleased() {
        if (shardReleasedBuilder_ == null) {
          shardReleased_ = null;
          onChanged();
        } else {
          shardReleasedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public ShardReleased.Builder getShardReleasedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getShardReleasedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      public ShardReleasedOrBuilder getShardReleasedOrBuilder() {
        if (shardReleasedBuilder_ != null) {
          return shardReleasedBuilder_.getMessageOrBuilder();
        } else {
          return shardReleased_ == null ?
              ShardReleased.getDefaultInstance() : shardReleased_;
        }
      }
      /**
       * <code>optional .org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased shardReleased = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ShardReleased, ShardReleased.Builder, ShardReleasedOrBuilder>
          getShardReleasedFieldBuilder() {
        if (shardReleasedBuilder_ == null) {
          shardReleasedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ShardReleased, ShardReleased.Builder, ShardReleasedOrBuilder>(
                  getShardReleased(),
                  getParentForChildren(),
                  isClean());
          shardReleased_ = null;
        }
        return shardReleasedBuilder_;
      }

      private long viewId_ ;
      /**
       * <code>optional int64 viewId = 2;</code>
       */
      public boolean hasViewId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       */
      public long getViewId() {
        return viewId_;
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       */
      public Builder setViewId(long value) {
        bitField0_ |= 0x00000002;
        viewId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 viewId = 2;</code>
       */
      public Builder clearViewId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        viewId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ClusterMessage)
    private static final ClusterMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClusterMessage();
    }

    public static ClusterMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ClusterMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClusterMessage>() {
      public ClusterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClusterMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClusterMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClusterMessage> getParserForType() {
      return PARSER;
    }

    public ClusterMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShardReleasedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 shardId = 1;</code>
     */
    boolean hasShardId();
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    int getShardId();

    /**
     * <code>optional string actorSystem = 2;</code>
     */
    boolean hasActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    String getActorSystem();
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    com.google.protobuf.ByteString
        getActorSystemBytes();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
   */
  public  static final class ShardReleased extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
      ShardReleasedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShardReleased.newBuilder() to construct.
    private ShardReleased(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShardReleased() {
      shardId_ = 0;
      actorSystem_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShardReleased(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              shardId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              actorSystem_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShardReleased.class, Builder.class);
    }

    private int bitField0_;
    public static final int SHARDID_FIELD_NUMBER = 1;
    private int shardId_;
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    public boolean hasShardId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 shardId = 1;</code>
     */
    public int getShardId() {
      return shardId_;
    }

    public static final int ACTORSYSTEM_FIELD_NUMBER = 2;
    private volatile Object actorSystem_;
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public boolean hasActorSystem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public String getActorSystem() {
      Object ref = actorSystem_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          actorSystem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string actorSystem = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActorSystemBytes() {
      Object ref = actorSystem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        actorSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, actorSystem_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, shardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, actorSystem_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ShardReleased)) {
        return super.equals(obj);
      }
      ShardReleased other = (ShardReleased) obj;

      boolean result = true;
      result = result && (hasShardId() == other.hasShardId());
      if (hasShardId()) {
        result = result && (getShardId()
            == other.getShardId());
      }
      result = result && (hasActorSystem() == other.hasActorSystem());
      if (hasActorSystem()) {
        result = result && getActorSystem()
            .equals(other.getActorSystem());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShardId()) {
        hash = (37 * hash) + SHARDID_FIELD_NUMBER;
        hash = (53 * hash) + getShardId();
      }
      if (hasActorSystem()) {
        hash = (37 * hash) + ACTORSYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getActorSystem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ShardReleased parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShardReleased parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShardReleased parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShardReleased parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShardReleased parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShardReleased parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShardReleased parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShardReleased parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShardReleased parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ShardReleased parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShardReleased parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ShardReleased prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
        ShardReleasedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ShardReleased.class, Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.cluster.protobuf.Clustering.ShardReleased.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        shardId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        actorSystem_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Clustering.internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
      }

      public ShardReleased getDefaultInstanceForType() {
        return ShardReleased.getDefaultInstance();
      }

      public ShardReleased build() {
        ShardReleased result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ShardReleased buildPartial() {
        ShardReleased result = new ShardReleased(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shardId_ = shardId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actorSystem_ = actorSystem_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ShardReleased) {
          return mergeFrom((ShardReleased)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ShardReleased other) {
        if (other == ShardReleased.getDefaultInstance()) return this;
        if (other.hasShardId()) {
          setShardId(other.getShardId());
        }
        if (other.hasActorSystem()) {
          bitField0_ |= 0x00000002;
          actorSystem_ = other.actorSystem_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ShardReleased parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ShardReleased) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int shardId_ ;
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public boolean hasShardId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public int getShardId() {
        return shardId_;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public Builder setShardId(int value) {
        bitField0_ |= 0x00000001;
        shardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shardId = 1;</code>
       */
      public Builder clearShardId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shardId_ = 0;
        onChanged();
        return this;
      }

      private Object actorSystem_ = "";
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public boolean hasActorSystem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public String getActorSystem() {
        Object ref = actorSystem_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            actorSystem_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public com.google.protobuf.ByteString
          getActorSystemBytes() {
        Object ref = actorSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          actorSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder setActorSystem(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actorSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder clearActorSystem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actorSystem_ = getDefaultInstance().getActorSystem();
        onChanged();
        return this;
      }
      /**
       * <code>optional string actorSystem = 2;</code>
       */
      public Builder setActorSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actorSystem_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.cluster.protobuf.ShardReleased)
    private static final ShardReleased DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ShardReleased();
    }

    public static ShardReleased getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ShardReleased>
        PARSER = new com.google.protobuf.AbstractParser<ShardReleased>() {
      public ShardReleased parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShardReleased(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShardReleased> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ShardReleased> getParserForType() {
      return PARSER;
    }

    public ShardReleased getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020clustering.proto\0222org.elasticsoftware." +
      "elasticactors.cluster.protobuf\"z\n\016Cluste" +
      "rMessage\022X\n\rshardReleased\030\001 \001(\0132A.org.el" +
      "asticsoftware.elasticactors.cluster.prot" +
      "obuf.ShardReleased\022\016\n\006viewId\030\002 \001(\003\"5\n\rSh" +
      "ardReleased\022\017\n\007shardId\030\001 \001(\005\022\023\n\013actorSys" +
      "tem\030\002 \001(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ClusterMessage_descriptor,
        new String[] { "ShardReleased", "ViewId", });
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_cluster_protobuf_ShardReleased_descriptor,
        new String[] { "ShardId", "ActorSystem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
