/*
 *   Copyright 2013 - 2019 The Original Authors
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package org.elasticsoftware.elasticactors.serialization.protobuf;

public final class Messaging {
  private Messaging() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string receiver = 1;</code>
     */
    boolean hasReceiver();
    /**
     * <code>optional string receiver = 1;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>optional string receiver = 1;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>optional string sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>optional string sender = 2;</code>
     */
    java.lang.String getSender();
    /**
     * <code>optional string sender = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>optional string payloadClass = 3;</code>
     */
    boolean hasPayloadClass();
    /**
     * <code>optional string payloadClass = 3;</code>
     */
    java.lang.String getPayloadClass();
    /**
     * <code>optional string payloadClass = 3;</code>
     */
    com.google.protobuf.ByteString
        getPayloadClassBytes();

    /**
     * <code>optional bytes payload = 4;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>optional bytes id = 5;</code>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 5;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>optional bool durable = 6;</code>
     */
    boolean hasDurable();
    /**
     * <code>optional bool durable = 6;</code>
     */
    boolean getDurable();

    /**
     * <code>optional bool undeliverable = 7;</code>
     */
    boolean hasUndeliverable();
    /**
     * <code>optional bool undeliverable = 7;</code>
     */
    boolean getUndeliverable();

    /**
     * <code>repeated string receivers = 8;</code>
     */
    java.util.List<java.lang.String>
        getReceiversList();
    /**
     * <code>repeated string receivers = 8;</code>
     */
    int getReceiversCount();
    /**
     * <code>repeated string receivers = 8;</code>
     */
    java.lang.String getReceivers(int index);
    /**
     * <code>repeated string receivers = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiversBytes(int index);

    /**
     * <code>optional uint32 timeout = 9;</code>
     */
    boolean hasTimeout();
    /**
     * <code>optional uint32 timeout = 9;</code>
     */
    int getTimeout();
  }
  /**
   * Protobuf type {@code org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage}
   */
  public  static final class InternalMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage)
      InternalMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalMessage.newBuilder() to construct.
    private InternalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMessage() {
      receiver_ = "";
      sender_ = "";
      payloadClass_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      id_ = com.google.protobuf.ByteString.EMPTY;
      durable_ = false;
      undeliverable_ = false;
      receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timeout_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              receiver_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sender_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              payloadClass_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              payload_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              id_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              durable_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              undeliverable_ = input.readBool();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                receivers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              receivers_.add(bs);
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              timeout_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          receivers_ = receivers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.class, org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.Builder.class);
    }

    private int bitField0_;
    public static final int RECEIVER_FIELD_NUMBER = 1;
    private volatile java.lang.Object receiver_;
    /**
     * <code>optional string receiver = 1;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string receiver = 1;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string receiver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object sender_;
    /**
     * <code>optional string sender = 2;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sender = 2;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOADCLASS_FIELD_NUMBER = 3;
    private volatile java.lang.Object payloadClass_;
    /**
     * <code>optional string payloadClass = 3;</code>
     */
    public boolean hasPayloadClass() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string payloadClass = 3;</code>
     */
    public java.lang.String getPayloadClass() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payloadClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payloadClass = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadClassBytes() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 4;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int ID_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 5;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes id = 5;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int DURABLE_FIELD_NUMBER = 6;
    private boolean durable_;
    /**
     * <code>optional bool durable = 6;</code>
     */
    public boolean hasDurable() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool durable = 6;</code>
     */
    public boolean getDurable() {
      return durable_;
    }

    public static final int UNDELIVERABLE_FIELD_NUMBER = 7;
    private boolean undeliverable_;
    /**
     * <code>optional bool undeliverable = 7;</code>
     */
    public boolean hasUndeliverable() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool undeliverable = 7;</code>
     */
    public boolean getUndeliverable() {
      return undeliverable_;
    }

    public static final int RECEIVERS_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList receivers_;
    /**
     * <code>repeated string receivers = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReceiversList() {
      return receivers_;
    }
    /**
     * <code>repeated string receivers = 8;</code>
     */
    public int getReceiversCount() {
      return receivers_.size();
    }
    /**
     * <code>repeated string receivers = 8;</code>
     */
    public java.lang.String getReceivers(int index) {
      return receivers_.get(index);
    }
    /**
     * <code>repeated string receivers = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiversBytes(int index) {
      return receivers_.getByteString(index);
    }

    public static final int TIMEOUT_FIELD_NUMBER = 9;
    private int timeout_;
    /**
     * <code>optional uint32 timeout = 9;</code>
     */
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 timeout = 9;</code>
     */
    public int getTimeout() {
      return timeout_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, receiver_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, payloadClass_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, payload_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, id_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, durable_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, undeliverable_);
      }
      for (int i = 0; i < receivers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receivers_.getRaw(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, timeout_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, receiver_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, payloadClass_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, id_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, durable_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, undeliverable_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < receivers_.size(); i++) {
          dataSize += computeStringSizeNoTag(receivers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getReceiversList().size();
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, timeout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage)) {
        return super.equals(obj);
      }
      org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage other = (org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage) obj;

      boolean result = true;
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && (hasPayloadClass() == other.hasPayloadClass());
      if (hasPayloadClass()) {
        result = result && getPayloadClass()
            .equals(other.getPayloadClass());
      }
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasDurable() == other.hasDurable());
      if (hasDurable()) {
        result = result && (getDurable()
            == other.getDurable());
      }
      result = result && (hasUndeliverable() == other.hasUndeliverable());
      if (hasUndeliverable()) {
        result = result && (getUndeliverable()
            == other.getUndeliverable());
      }
      result = result && getReceiversList()
          .equals(other.getReceiversList());
      result = result && (hasTimeout() == other.hasTimeout());
      if (hasTimeout()) {
        result = result && (getTimeout()
            == other.getTimeout());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasPayloadClass()) {
        hash = (37 * hash) + PAYLOADCLASS_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadClass().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasDurable()) {
        hash = (37 * hash) + DURABLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDurable());
      }
      if (hasUndeliverable()) {
        hash = (37 * hash) + UNDELIVERABLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUndeliverable());
      }
      if (getReceiversCount() > 0) {
        hash = (37 * hash) + RECEIVERS_FIELD_NUMBER;
        hash = (53 * hash) + getReceiversList().hashCode();
      }
      if (hasTimeout()) {
        hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
        hash = (53 * hash) + getTimeout();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage)
        org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.class, org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.Builder.class);
      }

      // Construct using org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        receiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        payloadClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        durable_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        undeliverable_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        timeout_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage getDefaultInstanceForType() {
        return org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage build() {
        org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage buildPartial() {
        org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage result = new org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payloadClass_ = payloadClass_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.durable_ = durable_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.undeliverable_ = undeliverable_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          receivers_ = receivers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.receivers_ = receivers_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.timeout_ = timeout_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage) {
          return mergeFrom((org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage other) {
        if (other == org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage.getDefaultInstance()) return this;
        if (other.hasReceiver()) {
          bitField0_ |= 0x00000001;
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000002;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasPayloadClass()) {
          bitField0_ |= 0x00000004;
          payloadClass_ = other.payloadClass_;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDurable()) {
          setDurable(other.getDurable());
        }
        if (other.hasUndeliverable()) {
          setUndeliverable(other.getUndeliverable());
        }
        if (!other.receivers_.isEmpty()) {
          if (receivers_.isEmpty()) {
            receivers_ = other.receivers_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureReceiversIsMutable();
            receivers_.addAll(other.receivers_);
          }
          onChanged();
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object receiver_ = "";
      /**
       * <code>optional string receiver = 1;</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000001);
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>optional string sender = 2;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sender = 2;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender = 2;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender = 2;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender = 2;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object payloadClass_ = "";
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public boolean hasPayloadClass() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public java.lang.String getPayloadClass() {
        java.lang.Object ref = payloadClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            payloadClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadClassBytes() {
        java.lang.Object ref = payloadClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payloadClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public Builder setPayloadClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payloadClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public Builder clearPayloadClass() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payloadClass_ = getDefaultInstance().getPayloadClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payloadClass = 3;</code>
       */
      public Builder setPayloadClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payloadClass_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 4;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 4;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 5;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes id = 5;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 5;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 5;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private boolean durable_ ;
      /**
       * <code>optional bool durable = 6;</code>
       */
      public boolean hasDurable() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool durable = 6;</code>
       */
      public boolean getDurable() {
        return durable_;
      }
      /**
       * <code>optional bool durable = 6;</code>
       */
      public Builder setDurable(boolean value) {
        bitField0_ |= 0x00000020;
        durable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool durable = 6;</code>
       */
      public Builder clearDurable() {
        bitField0_ = (bitField0_ & ~0x00000020);
        durable_ = false;
        onChanged();
        return this;
      }

      private boolean undeliverable_ ;
      /**
       * <code>optional bool undeliverable = 7;</code>
       */
      public boolean hasUndeliverable() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool undeliverable = 7;</code>
       */
      public boolean getUndeliverable() {
        return undeliverable_;
      }
      /**
       * <code>optional bool undeliverable = 7;</code>
       */
      public Builder setUndeliverable(boolean value) {
        bitField0_ |= 0x00000040;
        undeliverable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool undeliverable = 7;</code>
       */
      public Builder clearUndeliverable() {
        bitField0_ = (bitField0_ & ~0x00000040);
        undeliverable_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReceiversIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          receivers_ = new com.google.protobuf.LazyStringArrayList(receivers_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReceiversList() {
        return receivers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public int getReceiversCount() {
        return receivers_.size();
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public java.lang.String getReceivers(int index) {
        return receivers_.get(index);
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiversBytes(int index) {
        return receivers_.getByteString(index);
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public Builder setReceivers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiversIsMutable();
        receivers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public Builder addReceivers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiversIsMutable();
        receivers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public Builder addAllReceivers(
          java.lang.Iterable<java.lang.String> values) {
        ensureReceiversIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, receivers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public Builder clearReceivers() {
        receivers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receivers = 8;</code>
       */
      public Builder addReceiversBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiversIsMutable();
        receivers_.add(value);
        onChanged();
        return this;
      }

      private int timeout_ ;
      /**
       * <code>optional uint32 timeout = 9;</code>
       */
      public boolean hasTimeout() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 timeout = 9;</code>
       */
      public int getTimeout() {
        return timeout_;
      }
      /**
       * <code>optional uint32 timeout = 9;</code>
       */
      public Builder setTimeout(int value) {
        bitField0_ |= 0x00000100;
        timeout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timeout = 9;</code>
       */
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timeout_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage)
    }

    // @@protoc_insertion_point(class_scope:org.elasticsoftware.elasticactors.serialization.protobuf.InternalMessage)
    private static final org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage();
    }

    public static org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalMessage>
        PARSER = new com.google.protobuf.AbstractParser<InternalMessage>() {
      @java.lang.Override
      public InternalMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.elasticsoftware.elasticactors.serialization.protobuf.Messaging.InternalMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messaging.proto\0228org.elasticsoftware.e" +
      "lasticactors.serialization.protobuf\"\262\001\n\017" +
      "InternalMessage\022\020\n\010receiver\030\001 \001(\t\022\016\n\006sen" +
      "der\030\002 \001(\t\022\024\n\014payloadClass\030\003 \001(\t\022\017\n\007paylo" +
      "ad\030\004 \001(\014\022\n\n\002id\030\005 \001(\014\022\017\n\007durable\030\006 \001(\010\022\025\n" +
      "\rundeliverable\030\007 \001(\010\022\021\n\treceivers\030\010 \003(\t\022" +
      "\017\n\007timeout\030\t \001(\rB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_elasticsoftware_elasticactors_serialization_protobuf_InternalMessage_descriptor,
        new java.lang.String[] { "Receiver", "Sender", "PayloadClass", "Payload", "Id", "Durable", "Undeliverable", "Receivers", "Timeout", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
