# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI V6 Branch

on:
  push:
    branches:
      - elasticactors-v6
    paths-ignore:
      - '*.md'
      - 'LICENSE.txt'
  pull_request:
    branches:
      - elasticactors-v6
    paths-ignore:
      - '*.md'
      - 'LICENSE.txt'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    concurrency: ci-v6
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        check-latest: true
        settings-path: ${{ github.workspace }}
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn
        --show-version
        --batch-mode
        --no-transfer-progress
        --activate-profiles ci
        --file pom.xml
        --settings $GITHUB_WORKSPACE/settings.xml
        clean
        compile
        test-compile
        -U
    - name: Verify with Maven
      run: >
        mvn
        --show-version
        --batch-mode
        --no-transfer-progress
        --activate-profiles ci
        --file pom.xml
        --settings $GITHUB_WORKSPACE/settings.xml
        verify
        -U